apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-cluster-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: teleport-tls
  namespace: teleport
spec:
  secretName: tls-web
  commonName: teleport.example.com
  isCA: true
  issuerRef:
    name: selfsigning-issuer
    kind: ClusterIssuer
