apiVersion: v1
kind: ConfigMap
metadata:
  name: teleport
spec:
  teleport.yaml: |
    teleport:
      log:
        severity: INFO
        output: stderr
        format:
          output: text
          extra_fields: ["timestamp","level","component","caller"]
      storage:
        type: dir
    auth_service:
      enabled: true
      authentication:
        type: local
      public_addr: teleport.example.com:3025
      cluster_name: teleport.example.com
    ssh_service:
      enabled: true
      public_addr: teleport.example.com:3022
    proxy_service:
      enabled: true
      public_addr: teleport.example.com
      web_listen_addr: 0.0.0.0:3080
      listen_addr: 0.0.0.0:3023
      https_key_file: /var/lib/certs/tls.key
      https_cert_file: /var/lib/certs/tls.crt
      kubernetes:
        enabled: true
        listen_addr: 0.0.0.0:3026
